// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.quickjs

import lib.quickjs.proc.JSCFunction
import lib.quickjs.proc.JSCFunctionData
import lib.quickjs.proc.JSCFunctionMagic
import lib.quickjs.proc.JSClassCall
import lib.quickjs.proc.JSClassFinalizer
import lib.quickjs.proc.JSClassGCMark
import lib.quickjs.proc.JSFreeArrayBufferDataFunc
import lib.quickjs.proc.JSHostPromiseRejectionTracker
import lib.quickjs.proc.JSInterruptHandler
import lib.quickjs.proc.JSJobFunc
import lib.quickjs.proc.JSModuleInitFunc
import lib.quickjs.proc.JSModuleLoaderFunc
import lib.quickjs.proc.JSModuleNormalizeFunc
import lib.quickjs.proc.JS_MarkFunc

public typealias int16_t = Short

public typealias int32_t = Int

public typealias int64_t = Long

public typealias uint8_t = UByte

public typealias uint32_t = UInt

public typealias uint64_t = ULong

public typealias JSClassID = uint32_t

public typealias JSAtom = uint32_t

public typealias JSValue = uint64_t

public typealias JSCFunction = JSCFunction

public typealias JSCFunctionMagic = JSCFunctionMagic

public typealias JSCFunctionData = JSCFunctionData

public typealias JS_MarkFunc = JS_MarkFunc

public typealias JSClassFinalizer = JSClassFinalizer

public typealias JSClassGCMark = JSClassGCMark

public typealias JSClassCall = JSClassCall

public typealias JSFreeArrayBufferDataFunc = JSFreeArrayBufferDataFunc

public typealias JSHostPromiseRejectionTracker = JSHostPromiseRejectionTracker

public typealias JSInterruptHandler = JSInterruptHandler

public typealias JSModuleNormalizeFunc = JSModuleNormalizeFunc

public typealias JSModuleLoaderFunc = JSModuleLoaderFunc

public typealias JSJobFunc = JSJobFunc

public typealias JSModuleInitFunc = JSModuleInitFunc
