// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.quickjs

import java.lang.foreign.*

@JvmInline
public value class JSModuleDef(
    public val `$mem`: MemorySegment,
) {
    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
        ).withName("JSModuleDef")

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): JSModuleDef =
            JSModuleDef(alloc.allocate(layout))
    }
}
