// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.quickjs

import java.lang.foreign.*
import java.lang.invoke.VarHandle

@JvmInline
public value class JSPropertyEnum(
    public val `$mem`: MemorySegment,
) {
    public var is_enumerable: Int
        get() = is_enumerableHandle.get(this.`$mem`, 0L) as Int
        set(`value`) {
            is_enumerableHandle.set(this.`$mem`, 0L, value)
        }

    public var atom: JSAtom
        get() = (atomHandle.get(this.`$mem`, 0L) as Int).toUInt()
        set(`value`) {
            atomHandle.set(this.`$mem`, 0L, value.toInt())
        }

    public constructor(gc: Boolean) : this(kotlin.run {
        require(gc) { "Do not call this if gc is not want" }
        Arena.ofAuto().allocate(layout)
    })

    public companion object {
        public val layout: StructLayout = MemoryLayout.structLayout(
            ValueLayout.JAVA_INT.withName("is_enumerable"),
            ValueLayout.JAVA_INT.withName("atom"),
        ).withName("JSPropertyEnum")

        @JvmField
        public val is_enumerableHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("is_enumerable"))

        @JvmField
        public val atomHandle: VarHandle =
            layout.varHandle(MemoryLayout.PathElement.groupElement("atom"))

        @JvmStatic
        public fun allocate(alloc: SegmentAllocator): JSPropertyEnum =
            JSPropertyEnum(alloc.allocate(layout))
    }
}
