// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.quickjs

public object JSTag {
    public const val TAGFIRST: Int = -11
    public const val TAGBIGDECIMAL: Int = -11
    public const val TAGBIGINT: Int = -10
    public const val TAGBIGFLOAT: Int = -9
    public const val TAGSYMBOL: Int = -8
    public const val TAGSTRING: Int = -7
    public const val TAGMODULE: Int = -3
    public const val TAGFUNCTIONBYTECODE: Int = -2
    public const val TAGOBJECT: Int = -1
    public const val TAGINT: Int = 0
    public const val TAGBOOL: Int = 1
    public const val TAGNULL: Int = 2
    public const val TAGUNDEFINED: Int = 3
    public const val TAGUNINITIALIZED: Int = 4
    public const val TAGCATCHOFFSET: Int = 5
    public const val TAGEXCEPTION: Int = 6
    public const val TAGFLOAT64: Int = 7
}