// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.quickjs.proc

import lib.quickjs.`$RuntimeHelper`
import lib.quickjs.JSRuntime
import lib.quickjs.JSValue
import lib.quickjs.JS_MarkFunc
import lib.quickjs.Pointer
import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles

public fun interface JSClassGCMark {
    public fun invoke(
        rt: Pointer<JSRuntime>,
        `val`: JSValue,
        mark_func: Pointer<JS_MarkFunc>,
    )

    public fun allocate(arena: Arena): MemorySegment =
        Linker.nativeLinker().upcallStub(invokeHandle.bindTo(this), fd, arena)

    public companion object {
        @JvmStatic
        public val invokeHandle: MethodHandle =
            MethodHandles.lookup().unreflect(JSClassGCMark::class.java.methods.find {
                it.name == "invoke"
            }
            )

        @JvmStatic
        public val fd: FunctionDescriptor = FunctionDescriptor.ofVoid(
            `$RuntimeHelper`.POINTER,
            ValueLayout.JAVA_LONG,
            `$RuntimeHelper`.POINTER,
        )
    }
}
