// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.quickjs.proc

import lib.quickjs.`$RuntimeHelper`
import lib.quickjs.JSContext
import lib.quickjs.JSValue
import lib.quickjs.Pointer
import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles

public fun interface JSClassCall {
    public fun invoke(
        ctx: Pointer<JSContext>,
        func_obj: JSValue,
        this_val: JSValue,
        argc: Int,
        argv: Pointer<JSValue>,
        flags: Int,
    ): JSValue

    public fun allocate(arena: Arena): MemorySegment =
        Linker.nativeLinker().upcallStub(invokeHandle.bindTo(this), fd, arena)

    public companion object {
        @JvmStatic
        public val invokeHandle: MethodHandle =
            MethodHandles.lookup().unreflect(JSClassCall::class.java.methods.find {
                it.name == "invoke"
            }
            )

        @JvmStatic
        public val fd: FunctionDescriptor = FunctionDescriptor.of(
            ValueLayout.JAVA_LONG,
            `$RuntimeHelper`.POINTER,
            ValueLayout.JAVA_LONG,
            ValueLayout.JAVA_LONG,
            ValueLayout.JAVA_INT,
            `$RuntimeHelper`.POINTER,
            ValueLayout.JAVA_INT,
        )
    }
}
