// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.quickjs.proc

import lib.quickjs.`$RuntimeHelper`
import lib.quickjs.JSContext
import lib.quickjs.JSModuleDef
import lib.quickjs.Pointer
import java.lang.foreign.Arena
import java.lang.foreign.FunctionDescriptor
import java.lang.foreign.Linker
import java.lang.foreign.MemorySegment
import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles

public fun interface JSModuleLoaderFunc {
    public fun invoke(
        ctx: Pointer<JSContext>,
        module_name: Pointer<Byte>,
        opaque: Pointer<Unit>,
    ): Pointer<JSModuleDef>

    public fun allocate(arena: Arena): MemorySegment =
        Linker.nativeLinker().upcallStub(invokeHandle.bindTo(this), fd, arena)

    public companion object {
        @JvmStatic
        public val invokeHandle: MethodHandle =
            MethodHandles.lookup().unreflect(JSModuleLoaderFunc::class.java.methods.find {
                it.name == "invoke"
            }
            )

        @JvmStatic
        public val fd: FunctionDescriptor = FunctionDescriptor.of(
            `$RuntimeHelper`.POINTER,
            `$RuntimeHelper`.POINTER,
            `$RuntimeHelper`.POINTER,
            `$RuntimeHelper`.POINTER,
        )
    }
}
