// this file is auto generated by endoqa kotlin ffi, modify it with caution
package lib.quickjs.proc

import lib.quickjs.`$RuntimeHelper`
import lib.quickjs.JSContext
import lib.quickjs.JSModuleDef
import lib.quickjs.Pointer
import java.lang.foreign.*
import java.lang.invoke.MethodHandle
import java.lang.invoke.MethodHandles

public fun interface JSModuleInitFunc {
    public fun invoke(ctx: Pointer<JSContext>, m: Pointer<JSModuleDef>): Int

    public fun allocate(arena: Arena): MemorySegment =
        Linker.nativeLinker().upcallStub(invokeHandle.bindTo(this), fd, arena)

    public companion object {
        @JvmStatic
        public val invokeHandle: MethodHandle =
            MethodHandles.lookup().unreflect(JSModuleInitFunc::class.java.methods.find {
                it.name == "invoke"
            }
            )

        @JvmStatic
        public val fd: FunctionDescriptor = FunctionDescriptor.of(
            ValueLayout.JAVA_INT,
            `$RuntimeHelper`.POINTER,
            `$RuntimeHelper`.POINTER,
        )
    }
}
